# Travis CI Settings

language: python

python:
  - "2.7"
  - "pypy"

script:
  - nosetests --with-coverage --cover-package=nvm

after_success:
  - coveralls

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y uuid-dev
  - wget https://github.com/pmem/nvml/archive/master.tar.gz
  - tar -xzvf master.tar.gz
  - cd nvml-master && make && sudo make install
  - sudo ldconfig

install: 
  - pip install coveralls
  - cd $TRAVIS_BUILD_DIR && python setup.py develop
